const DataType = {
    Bit: "Bit",
    TinyInt: "TinyInt",
    SmallInt: "SmallInt",
    Int: "Int",
    BigInt: "BigInt",
    Numeric: "Numeric",
    Decimal: "Decimal",
    SmallMoney: "SmallMoney",
    Money: "Money",
    Float: "Float",
    Real: "Real",
    SmallDateTime: "SmallDateTime",
    DateTime: "DateTime",
    DateTime2: "DateTime2",
    DateTimeOffset: "DateTimeOffset",
    Time: "Time",
    Date: "Date",
    Char: "Char",
    VarChar: "VarChar",
    Text: "Text",
    NChar: "NChar",
    NVarChar: "NVarChar",
    NText: "NText",
    Binary: "Binary",
    VarBinary: "VarBinary",
    Image: "Image",
    Null: "Null",
    TVP: "TVP",
    UDT: "UDT",
    UniqueIdentifier: "UniqueIdentifier",
    Variant: "Variant",
    xml: "xml"
}

module.exports = DataType